language: go
sudo: required

go:
  - 1.7

script:
  ### build and push standalone aci
  - make clean build_travis_standalone_aci
  - mv binder.aci binder-latest-linux-amd64.aci
  # pull unixvoid gpg keys
  - curl -d sec=$BINDER_SEC -d key=unixvoid.pub https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  # sign aci
  - cp deps/sign.sh . && chmod +x sign.sh
  - ./sign.sh $GPG_SEC
  # upload binder aci image
  - curl -i --form sec=$BINDER_SEC --form file=@binder-latest-linux-amd64.aci --form path=rkt/binder/standalone/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@binder-latest-linux-amd64.aci.asc --form path=rkt/binder/standalone/ https://cryo.unixvoid.com/upload
